name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'maven'
          maven-version: '3.8.5'

      - name: Build with Maven
        run: mvn clean install

      - name: Create settings.xml
        run: |
          mkdir -p ~/.m2
          echo '<settings><servers><server><id>central</id><username>${{ secrets.CENTRAL_USER_NAME }}</username><password>${{ secrets.CENTRAL_PASSWORD }}</password></server></servers></settings>' > ~/.m2/settings.xml
          
      - name: Build with Maven
        run: mvn clean deploy