name: CI for CentralPortalPublish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create settings.xml
        run: |
          mkdir -p ~/.m2
          echo '<settings><servers><server><id>central</id><username>${secrets.CENTRAL_USER_NAME}</username><password>${secrets.CENTRAL_PASSWORD}</password></server></servers></settings>' > ~/.m2/settings.xml

      - name: Print working directory and list files
        run: |
          pwd
          ls -la

      - name: Build with Maven
        working-directory: centralportalpublish
        run: mvn clean deploy