name: CI for CentralPortalPublish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" > private.key
          gpg --batch --import private.key
      - name: Verify GPG Key
        run: |
          gpg --list-keys
          gpg --list-secret-keys
      - name: Configure Maven for GPG
        run: |
          mkdir -p $HOME/.m2
          echo "<settings>
            <servers>
              <server>
                <id>gpg.passphrase</id>
                <passphrase>\${env.GPG_PASSPHRASE}</passphrase>
              </server>
            </servers>
          </settings>" > $HOME/.m2/settings-security.xml
      - name: Build with Maven
        working-directory: centralportalpublish
        run: mvn clean deploy -B -Dgpg.skip=false
      - name: Verify GPG Signing
        run: gpg --list-keys && gpg --list-secret-keys