name: CI for CentralPortalPublish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create settings.xml
        run: |
          mkdir -p ~/.m2
          echo '<settings><servers><server><id>central</id><username>${{ secrets.CENTRAL_USER_NAME }}</username><password>${{ secrets.CENTRAL_PASSWORD }}</password></server></servers></settings>' > ~/.m2/settings.xml

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PASSPHRASE" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --edit-key $(gpg --list-keys --with-colons | awk -F: '/^pub/ { print $5 }') trust quit
      - name: Configure Maven for GPG
        run: |
          mkdir -p $HOME/.m2
          echo "<settings>
            <servers>
              <server>
                <id>gpg.passphrase</id>
                <passphrase>\${env.GPG_PASSPHRASE}</passphrase>
              </server>
            </servers>
          </settings>" > $HOME/.m2/settings.xml
      - name: Build with Maven
        run: mvn clean deploy -B -Dgpg.skip=false
      - name: Verify GPG Signing
        run: gpg --list-keys && gpg --list-secret-keys





