name: CI for CentralPortalPublish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | tr -d '\r' | gpg --batch --import
          echo "no-tty" >> ~/.gnupg/gpg.conf
          echo "batch" >> ~/.gnupg/gpg.conf

      - name: Set GPG key trust level
        run: |
          KEY_ID=$(gpg --list-keys --with-colons | awk -F: '/^pub/ { print $5 }')
          echo -e "5\ny\n" | gpg --command-fd 0 --batch --yes --edit-key $KEY_ID trust

      - name: Configure Maven for GPG
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: |
          mkdir -p $HOME/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>central</id>
                      <username>$CENTRAL_USERNAME</username>
                      <password>$CENTRAL_PASSWORD</password>
                    </server>
                    <server>
                      <id>gpg.passphrase</id>
                      <passphrase>$GPG_PASSPHRASE</passphrase>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>gpg</id>
                      <properties>
                        <gpg.executable>gpg</gpg.executable>
                        <gpg.keyname>alidoran</gpg.keyname>
                        <gpg.passphraseServerId>gpg.passphrase</gpg.passphraseServerId>
                      </properties>
                    </profile>
                  </profiles>
                  <activeProfiles>
                    <activeProfile>gpg</activeProfile>
                  </activeProfiles>
                </settings>" > $HOME/.m2/settings-security.xml
      - name: Build with Maven and sign artifacts
        env:
          GPG_TTY: $(tty)
        working-directory: centralportalpublish
        run: mvn clean deploy -B -Dgpg.skip=false -Dgpg.useagent=true