name: CI for CentralPortalPublish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Configure GPG key (replace with your actual GPG key ID)
      - name: Import GPG key
        env:
          GPG_KEY_ID: "YOUR_GPG_KEY_ID"  # Replace with your actual key ID
        run: |
          echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --trust-model always --import -
      # Configure GPG to use a non-interactive passphrase
      - name: Configure GPG passphrase
        run: |
          echo "quiet" >> ~/.gnupg/gpg.conf
          echo "disable-sanity" >> ~/.gnupg/gpg.conf
          echo "passphrase-fd 2" >> ~/.gnupg/gpg.conf
      # Add GPG passphrase as a secret (store securely)
      - name: Add GPG passphrase secret
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: echo ""
      # Build and deploy with GPG signing
      - name: Build and deploy with GPG signing
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "${GPG_PASSPHRASE}" | gpg --quiet --batch --passphrase-fd 0 --command-fd 1  --trust-model always --edit-key $GPG_KEY_ID sign
          mvn clean deploy -DskipTests # Optional: skip tests for faster build (adjust as needed)